### ISSUE TITLE
Getting started fails on Mac OS Big Sur

### ISSUE THREAD

**Issue by jschank** [blakemcbride/Kiss#1]
Tried following start up.

```
❯ ./bld develop
Failed to execute process './bld'. Reason:
exec: Exec format error
The file './bld' is marked as an executable but could not be run by the operating system.
```

**Comment by blakemcbride** [comment]
Hi.  Sorry about the trouble.  'bld' is a shell script - not a binary file.

I've tested the entire system on a bit older Macs and it ran fine.  I don't have Big Sur.

The file 'bld' starts with:
#

Try changing that first line to:
#! /bin/bash

Please let me know if that fixes the problem.

Thanks!

**Comment by blakemcbride** [comment]
Another thought.  Be sure you have the following commands available from your command prompt:

java
javac
javadoc
jar

These are all part of a standard JDK (Java Developer kit) install.

**Comment by blakemcbride** [comment]
Lastly, and most importantly, I see your prompt is '>'.  That's odd.  It should be '$'.  Are you running the 'Terminal' program?  This should be run in the 'Terminal' program (the command prompt).

**Comment by blakemcbride** [comment]
I just had someone with Big Sur test KISS..  They said it ran fine.  

Did a little research.  It seems the fish shell has the '>' prompt.  That could cause this problem.

I committed a change to the bld program that may solve your issue.  Please test and let me know.

If it doesn't, I'd suggest (at least temporarily) switching to the bash shell.  You may be able to do that by simply typing:  bash

**Comment by jschank** [comment]
Heh, honestly I didn’t even look at the file contents.
It is missing the shebang.

Instead of what you suggested, I used #! /usr/bin/env bash

Which I think might be better. Or the same. only long-bearded unix gurus know for sure.

In anycase, it works now. So probably you just need to add an appropriate shebang :)

Thanks for the quick reply.

John

**Comment by blakemcbride** [comment]
Hi John.  Thanks for the feedback!  I added the shebang.
