### ISSUE TITLE
bld fails with current clone

### ISSUE THREAD

**Issue by JJWeaver808** [blakemcbride/Kiss#5]
Hi Blake,
Started with completely clean setup, as instructed (Windows 10).  Failed with error as seen here:

Microsoft Windows [Version 10.0.19045.2486]
(c) Microsoft Corporation. All rights reserved.

C:\Users\JJWeaver>cd \

C:\>cd kiss
The system cannot find the path specified.

C:\>git clone https://github.com/blakemcbride/Kiss.git
Cloning into 'Kiss'...
remote: Enumerating objects: 8348, done.
remote: Counting objects: 100% (777/777), done.
remote: Compressing objects: 100% (319/319), done.
remote: Total 8348 (delta 435), reused 695 (delta 358), pack-reused 7571
g objects:  99% (8265/8348), 22.88 MiB | 784.00 KiB/s
Receiving objects: 100% (8348/8348), 23.08 MiB | 748.00 KiB/s, done.
Resolving deltas: 100% (5363/5363), done.

C:\>cd kiss

C:\Kiss>build-builder
C:\Kiss>bld develop
javac -g @C:\Users\JJWeaver\AppData\Local\Temp\Dependencies-7978930566700902005.inp -sourcepath src/main/core -d build.work/exploded/WEB-INF/classes @C:\Users\JJWeaver\AppData\Local\Temp\SourceFiles-612234151402369487.inp
src\main\core\org\kissweb\database\Command.java:35: error: cannot access JSONArray
import org.json.JSONArray;
               ^
  bad class file: libs\json.jar(org/json/JSONArray.class)
    class file has wrong version 61.0, should be 52.0
    Please remove or make sure it appears in the correct subdirectory of the classpath.
error executing javac -g @C:\Users\JJWeaver\AppData\Local\Temp\Dependencies-7978930566700902005.inp -sourcepath src/main/core -d build.work/exploded/WEB-INF/classes @C:\Users\JJWeaver\AppData\Local\Temp\SourceFiles-612234151402369487.inp
error executing task develop
C:\Kiss>

I did fiind a workaround by replacing /libs/json.jar with an earlier version of json.jar

Thanks,
Jim W.

**Comment by blakemcbride** [comment]
Thanks for the feedback.  I do most of my work and testing on Linux.  I only test on Windows periodically.  I just tested a clean install on Linux.  Worked perfectly.  I'll dig in on the Windows setup.

Thanks for the feedback.  I'll likely have it corrected today.

**Comment by blakemcbride** [comment]
I see the problem.  I built json.jar with Java version 17.  You're likely using an earlier version.  I will update json.jar with a version of json.jar built with Java 8.  Thanks.

**Comment by blakemcbride** [comment]
The problem has been corrected.  Thanks for the report!!
