### ISSUE TITLE
bld fails

### ISSUE THREAD

**Issue by afkirzak** [blakemcbride/Kiss#7]
Hi Blake,
Started with completely clean setup, as instructed (CentOS Linux). Failed with error as seen here:

`./bld develop
Downloading libs/c3p0-0.9.5.5.jar
error downloading c3p0-0.9.5.5.jar
error executing task develop`

**Comment by blakemcbride** [comment]
Thanks for the heads up.  I have it cached locally so I hadn't noticed that that dependency isn't there anymore.  I'll fix it shortly.  Thanks for the report!

**Comment by blakemcbride** [comment]
I just tried it from scratch.  It downloaded c3po just fine.  Could it be that you are having an internet connection problem?
